# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Data.Quests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos import Enums_pb2 as POGOProtos_dot_Enums__pb2

from POGOProtos.Enums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos.Data.Quests.proto',
  package='POGOProtos.Data.Quests',
  syntax='proto3',
  serialized_pb=_b('\n\x1cPOGOProtos.Data.Quests.proto\x12\x16POGOProtos.Data.Quests\x1a\x16POGOProtos.Enums.proto\"I\n\nDailyQuest\x12\x1d\n\x15\x63urrent_period_bucket\x18\x01 \x01(\x05\x12\x1c\n\x14\x63urrent_streak_count\x18\x02 \x01(\x05\"q\n\x05Quest\x12/\n\nquest_type\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.QuestType\x12\x37\n\x0b\x64\x61ily_quest\x18\x02 \x01(\x0b\x32\".POGOProtos.Data.Quests.DailyQuestP\x00\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums__pb2.DESCRIPTOR,],
  public_dependencies=[POGOProtos_dot_Enums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DAILYQUEST = _descriptor.Descriptor(
  name='DailyQuest',
  full_name='POGOProtos.Data.Quests.DailyQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_period_bucket', full_name='POGOProtos.Data.Quests.DailyQuest.current_period_bucket', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_streak_count', full_name='POGOProtos.Data.Quests.DailyQuest.current_streak_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=153,
)


_QUEST = _descriptor.Descriptor(
  name='Quest',
  full_name='POGOProtos.Data.Quests.Quest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quest_type', full_name='POGOProtos.Data.Quests.Quest.quest_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daily_quest', full_name='POGOProtos.Data.Quests.Quest.daily_quest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=268,
)

_QUEST.fields_by_name['quest_type'].enum_type = POGOProtos_dot_Enums__pb2._QUESTTYPE
_QUEST.fields_by_name['daily_quest'].message_type = _DAILYQUEST
DESCRIPTOR.message_types_by_name['DailyQuest'] = _DAILYQUEST
DESCRIPTOR.message_types_by_name['Quest'] = _QUEST

DailyQuest = _reflection.GeneratedProtocolMessageType('DailyQuest', (_message.Message,), dict(
  DESCRIPTOR = _DAILYQUEST,
  __module__ = 'POGOProtos.Data.Quests_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Data.Quests.DailyQuest)
  ))
_sym_db.RegisterMessage(DailyQuest)

Quest = _reflection.GeneratedProtocolMessageType('Quest', (_message.Message,), dict(
  DESCRIPTOR = _QUEST,
  __module__ = 'POGOProtos.Data.Quests_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Data.Quests.Quest)
  ))
_sym_db.RegisterMessage(Quest)


# @@protoc_insertion_point(module_scope)
